

import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { dark, neobrutalism, shadesOfPurple } from '@clerk/themes'
import Page, { ModeToggle } from './page'
import Topbar from '../components/shared/Topbar'

//oklch(0.1663 0.033 229.71)

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'WorkUp. Find your perfect role',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider 
      appearance={{
        baseTheme: dark,
        variables: { colorPrimary: 'white', colorText:'white',colorBackground:'#00111A',fontSize:'0.93rem' },
        
      }}>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}>
          <ThemeProvider attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange>
              <div className='flex-row'>
                <Topbar/>
              </div>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}